# main.py — Generated by VIA for: Build me an AI powered resume analyzer that scores resumes and gives improvement tips
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

import os

app = FastAPI(
    title="Build Me An Ai Powered Resume",
    description="Generated by VIA — Autonomous AI Digital Team",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

items_data = [{"id": 1, "title": "Sample", "status": "active", "description": "Auto-generated"}]

@app.get("/")
def root():
    return {"app": "Build Me An Ai Powered Resume", "status": "running", "generated_by": "VIA"}

@app.get("/health")
def health():
    return {"status": "healthy"}


@app.get("/api/v1/items")
def get_items():
    return {"items": items_data, "total": len(items_data)}

@app.get("/api/v1/items/{item_id}")
def get_item(item_id: int):
    item = next((i for i in items_data if i["id"] == item_id), None)
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return item

@app.post("/api/v1/items")
def create_item(item: dict):
    item["id"] = len(items_data) + 1
    items_data.append(item)
    return item

@app.put("/api/v1/items/{item_id}")
def update_item(item_id: int, update: dict):
    for i, item in enumerate(items_data):
        if item["id"] == item_id:
            items_data[i].update(update)
            return items_data[i]
    raise HTTPException(status_code=404, detail="Item not found")

@app.delete("/api/v1/items/{item_id}")
def delete_item(item_id: int):
    global items_data
    items_data = [i for i in items_data if i["id"] != item_id]
    return {"deleted": item_id}

@app.get("/api/v1/stats")
def get_stats():
    return {"total": len(items_data), "active": sum(1 for i in items_data if i.get("status") == "active")}


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=False)
